sudo: false
language: r
cache: packages
install:
  - Rscript -e 'install.packages("devtools");install.packages("/tmp/RtmpAuTRET/downloaded_packages")'
script:
  - Rscript -e 'devtools::check("RPackage")'
