sudo: false
language: r
cache: packages
install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("myfirstpackage")'
script:
  - Rscript -e 'devtools::check("myfirstpackage")'
