sudo: false
language: r
cache: packages
install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("my_first_package")'
script:
  - Rscript -e 'devtools::check("my_first_package")'
